db.guides.insertMany([
{
    title: "Soil",
    body: ["Healthy soil is the basis of healthy plants and a successful garden. When soil is in good shape there is less need for fertilizers or pesticides. Good soil is rich in humus which comes from decaying organic compost. It is loose and fluffy, holds moisture, drains well, and has plenty of minerals essential for plant growth. Living organisms like earthworms, certain fungi, and bacteria also help maintain the quality of the soil.",
        "Finding the right fertilizer for your soil is another important aspect. Macronutrients such as nitrogen, phosphorous, potassium, magnesium, calcium, sulfur are important to plant health. Micronutrients like boron, iron, zinc, etc are also important, in smaller quantities, to the health of your plants. A good balance together not only assure healthy growth, but they also help your plants fight off pests and diseases.",
        "The final touch for the perfect soil composition is proper pH. Although other aspects such as soil nutrients are largely important, soil pH still plays its part. A good way to test soil pH is to mix some soil with distilled water in a container until muddy, and then add vinegar. If it fizzes then your soil is too acidic. If that is the case, adding some pulverized limestone, which has magnesium and calcium carbonate, will raise the pH of your soil. Usually the natural pH of soil is between 6-7, so you should not have to worry.",
        "Always remember, a great way to keep your garden soil rich is by adding organic compost. Things like grass clippings, leaves, plants trimmings, table scraps, etc are excellent use for compost. These items contain various amounts of micronutrients, and their use in compost guarantees returning those micronutrients to the soil."],
    photoLink: "http://sustainablepulse.com/wp-content/uploads/2017/10/soil2.jpg"
}, {
    title: "Pest Control",
    body: ["Pest control is important to the success of any garden. Some larger animals such as raccoons and deer can be blocked by simply fencing in the garden area. The most common form of pests are usually bugs. The best way to prevent insect damage in your garden is to disuade them from approaching at all. In this case, a healthy garden is the best defence.",
        "Minimize insect habitat. Start by pulling out any weak plants as these may already be infected. Even if not, they will soon attract predators. Remove these plants and dispose of them away from the garden area. Clear garden area of debris and weeds which are breeding places for insects and use clean mulch. If you've been working with infested plants, clean your tools before moving on to other garden areas. This will reduce the speed of invading insects.",
        "Build healthy, organic soil. Natural composting methods, mulching and top-dressing your soil with compost or natural fertilizer is the best way to develop strong, resistant plants. Seaweed mulch or spray contains trace micronutrients such as iron, zinc, barium, calcium, sulfur and magnesium, which promote healthy development in plants. These nutrients enhance growth and give plants the resilience to withstand disease.",
        "Keep plant foliage dry. Wet foliage encourages insect and fungal damage to your plants. Optionally, invest in drip-irrigation for methods of delivering water directly to the roots without wetting the foliage. Interplant and rotate crops. Insect pests are often plant specific. When plantings are mixed, pests are less likely to spread throughout a crop. Rotating plants each year is a common method to avoid re-infestation of pests that have settled over winter.",
        "Always keep in mind some bugs are beneficial to your garden. Ladybugs eat the harmful insects, and bees pollinate your plants. So remember, be kind to these bugs!"],
    photoLink: "http://www.backyardnature.net/pix/b-swal-c.jpg"
}
])