use gardynbase
db.guides.remove({})
db.guides.insertMany([
{
    title: "Soil",
    body: ["Healthy soil is the basis of healthy plants and a successful garden. When soil is in good shape there is less need for fertilizers or pesticides. Good soil is rich in humus which comes from decaying organic compost. It is loose and fluffy, holds moisture, drains well, and has plenty of minerals essential for plant growth. Living organisms like earthworms, certain fungi, and bacteria also help maintain the quality of the soil.",
        "Finding the right fertilizer for your soil is another important aspect. Macronutrients such as nitrogen, phosphorous, potassium, magnesium, calcium, sulfur are important to plant health. Micronutrients like boron, iron, zinc, etc are also important, in smaller quantities, to the health of your plants. A good balance together not only assure healthy growth, but they also help your plants fight off pests and diseases.",
        "The final touch for the perfect soil composition is proper pH. Although other aspects such as soil nutrients are largely important, soil pH still plays its part. A good way to test soil pH is to mix some soil with distilled water in a container until muddy, and then add vinegar. If it fizzes then your soil is too acidic. If that is the case, adding some pulverized limestone, which has magnesium and calcium carbonate, will raise the pH of your soil. Usually the natural pH of soil is between 6-7, so you should not have to worry.",
        "Always remember, a great way to keep your garden soil rich is by adding organic compost. Things like grass clippings, leaves, plants trimmings, table scraps, etc are excellent use for compost. These items contain various amounts of micronutrients, and their use in compost guarantees returning those micronutrients to the soil."],
    photoLink: "http://earth-lite.com/wp-content/uploads/2014/07/DIRT2.jpg"
}, {
    title: "Pest Control",
    body: ["Pest control is important to the success of any garden. Some larger animals such as raccoons and deer can be blocked by simply fencing in the garden area. The most common form of pests are usually bugs. The best way to prevent insect damage in your garden is to disuade them from approaching at all. In this case, a healthy garden is the best defence.",
        "Minimize insect habitat. Start by pulling out any weak plants as these may already be infected. Even if not, they will soon attract predators. Remove these plants and dispose of them away from the garden area. Clear garden area of debris and weeds which are breeding places for insects and use clean mulch. If you've been working with infested plants, clean your tools before moving on to other garden areas. This will reduce the speed of invading insects.",
        "Build healthy, organic soil. Natural composting methods, mulching and top-dressing your soil with compost or natural fertilizer is the best way to develop strong, resistant plants. Seaweed mulch or spray contains trace micronutrients such as iron, zinc, barium, calcium, sulfur and magnesium, which promote healthy development in plants. These nutrients enhance growth and give plants the resilience to withstand disease.",
        "Keep plant foliage dry. Wet foliage encourages insect and fungal damage to your plants. Optionally, invest in drip-irrigation for methods of delivering water directly to the roots without wetting the foliage. Interplant and rotate crops. Insect pests are often plant specific. When plantings are mixed, pests are less likely to spread throughout a crop. Rotating plants each year is a common method to avoid re-infestation of pests that have settled over winter.",
        "Always keep in mind some bugs are beneficial to your garden. Ladybugs eat the harmful insects, and bees pollinate your plants. So remember, be kind to these bugs!"],
    photoLink: "http://1.bp.blogspot.com/-M-Zf9Wq6gUs/Ui0PLa5krMI/AAAAAAAAFFw/HQTTqp0i6jM/s1600/Tomato-Hornworm-in-Urban-Garden.png"
}, {
    title: "Watering 101",
    body: ["Watering your garden the right amount is key for your garden. Watering both too little and too much can increase the chance of disease. The amount you should water each plant isn't fixed, and will change with the size of each plant. Here are a few tips to help determine when to water and how much to use.",
        "Let's start by knowing how much to water. Ultimately, you want to water enough so that the water reaches the root of the plant. If there are more roots, you need more water. It helps to water around the base of the plant, avoiding getting the leaves wet (this can lead to disease). The soil doesn't always have to be moist, and depending on your soil composition, a lot of water will remain in the soil afterwards.",
        "What time of day you water won't siginifaicantly alter how your plants grow, but watering in the morning as opposed to afternoon typically means the water will evaporate slower due to the lower soil temperature.",
        "Lastly, don't overdo it. When starting a garden, you may be tempted to do evreything you can to ensure it grows well. Many people tend to overwater their plants because of this. Water on the leaves and just too much water in general lead to an environment prone to disease. Some diseases won't affect the yield, but others can be devastating. Watering in a large quantity one to two times a week is typically fine, and always take into account any water that your garden recieved from rain."
    ],
    photoLink: "https://previews.123rf.com/images/horten/horten1205/horten120500004/13472240-Water-pouring-from-orange-watering-can-onto-blooming-garden-strawberry-Stock-Photo.jpg"
}
])