db.plants.insertMany([
{
    "title": "Tomatoes",
    "imageURL": "http://assets.nydailynews.com/polopoly_fs/1.2834910.1476795531!/img/httpImage/image.jpg_gen/derivatives/article_750/488059328.jpg",
    "climate": "warm",
    "sunlight": "6 - 8 Hours",
    "spacing": "24 - 36 Inches",
    "support": true,
    "difficulty": "beginner",
    "special": ["Tomatoes need warmth; plant in late spring and early summer for most breeds. Recommend burying two-thirds of the stem when planting. Note method of deep planting only works with tomatoes.\n",
        "Tomato plants need 1 to 2 inches of water per week. Uneven watering can set the stage for blossom-end rot and may also cause fruits to crack open.\n",
        "Tomatoes have two types of growth: determinate and indeterminate. Determinate tomato plants stop growing at a certain size. They tend to set and produce all their fruit at once over a 2 to 3 week period. Often called bush tomatoes, they can be planted closer together and do well in a container.\n",
        "An indeterminate tomato plant will keep on growing and producing fruit until it is killed by frost. These plants get quite large and will need some kind of support. Whether you use a trellis, stakes, or cages is up to you, but supporting them is necessary to keep the plants from sprawling on the ground.\n"],
    "parentLevel": true,
    "parentCat": null,
    "isCat": false
}, {
    "title": "Broccoli",
    "imageURL": "https://www.cookforyourlife.org/wp-content/uploads/2015/08/shutterstock_294838064-min.jpg",
    "climate": "cool",
    "sunlight": "6 - 10 Hours",
    "spacing": "16 - 24 Inches",
    "support": false,
    "difficulty": "expert",
    "special": ["Water frequently, keep up moisture but do not wet head.",
        "Broccoli is a cool-season crop that, like spinach, can be grown in the spring or fall. Broccoli can germinate in soil with temperatures as low as 40°F.",
        "Fertilize three weeks after transplanting. Provide consistent soil moisture with regular watering, especially in drought conditions. Some varieties of broccoli are heat tolerant, but all need moisture. Do not get developing heads wet when watering. Roots are very shallow, do not cultivate. Use mulch to keep soil temperature low.",
        "Harvest broccoli when the buds of the head are firm and tight before the heads flower. If you do see yellow petals, harvest immediately. For best taste, harvest in the morning before the soil heats up. Cut heads from the plant. taking at least 6 inches of stem."],
    "parentLevel": true,
    "parentCat": null,
    "isCat": false
}, {
    "title": 'Radishes',
    "imageURL": "http://s3.amazonaws.com/finecooking.s3.tauntonclud.com/app/uploads/2017/04/24171905/ING-radish-thumb1x1.jpg",
    "climate": 'cool',
    "sunlight": "6 - 10 Hours",
    "spacing": '12 - 16 Inches',
    "support": false,
    "difficulty": "beginner",
    "special": ["Plant 4-6 weeks before the average date of last frost, after aged manure or organic fertilizer has been worked into soil. Prepare a light, well-drained soil with a pH of 5.8 to 6.8 for best production. When preparing the soil, avoid fresh manure and organic materials or fertilizers high in nitrogen.",
        "Water moderately. If the soil is too dry, radishes will bolt and become pithy and too pungent to eat. If too wet, the roots will split and rot. Never let the soil dry out, but don't keep it mucky, either.",
        "Radishes need sun. If they are planted in too much shade—or even where neighboring vegetable plants shade them—they put all their energy into producing larger leaves.",
        "There are two main types of radishes, spring radishes and winter radishes. Avoid warm weather, radishes do not thrive above 65°F."],
    "parentLevel": true,
    "parentCat": null,
    "isCat": false
}, {
    "title": "Beans",
    "imageURL": "http://suttons.s3.amazonaws.com/p/VEBEA25890rt_3.jpg",
    "climate": "cool",
    "sunlight": "6 - 8 Hours",
    "spacing": "6 - 10 Inches",
    "support": true,
    "difficulty": "beginner",
    "special": ["Seeds can be sown outdoors anytime after the last spring frost; minimum soil temperature is 48 degrees F. Plant 1 inch deep in normal soil, and a little deeper for sandier soils. Cover soil to warm if necessary. Do not start seeds indoors; they may not survive transplanting.",
        "Pole beans will grow as a climbing vine that may reach up to 15 feet tall. Therefore, pole beans require a trellis or staking. Bush beans will spread up to 2 feet, but do not require support.",
        "Water intensively once a week.",
        "Beans generally don't need extra nitrogen for good growth because the beneficial bacteria that live in nodules on bean roots help to provide nitrogen for the plants. To speed up growth, give beans—particularly long-bearing pole beans or heavy-feeding limas—a midseason side-dressing of compost or kelp extract solution.",
        "Beans are picked at an immature stage, when the seeds inside have not yet fully developed. Look for firm, sizable pods and snap or cut off the plant. Do not tear the plant. Fresh beans should snap easily when broken."],
    "parentLevel": true,
    "parentCat": null,
    "isCat": false
}, {
    "title": "B. Sprouts",
    "imageURL": "http://www.well-beingsecrets.com/wp-content/uploads/Brussels-Sprouts-and-Manganese.jpg",
    "climate": "cool",
    "sunlight": "6 - 10 Hours",
    "spacing": "18 - 24 Inches",
    "support": false,
    "difficulty": "intermediate",
    "special": ["Growing Brussels sprouts requires cool weather. The ideal climate is the “fog belt” of the Pacific Northwest, but they will grow in just about any part of the country. Start seeds indoors 6–8 weeks before last spring frost. While starting seeds indoors is recommended, you may also direct sow seeds 4 months before the first fall frost. You may also have luck finding seedlings at a nursery.",
        "Raised beds are especially recommended for cold season vegetables, especially when seasons are changing and temps are not consistent. Work fertilizer into soil a few days before planting or transplanting. Plant transplanted seedlings 12–24 inches apart.",
        "Fertilize three weeks after transplanting. Mulch to retain moisture and keep the soil temperature cool. Do not cultivate, roots are shallow and susceptible to damage.",
        "Brussels sprouts also need more boron than most other vegetables. If your brussels sprouts develop hollow stems and small buds, you can add boron to the soil by dissolving 1 level tablespoon of borax in 5 quarts of water and sprinkling it evenly over 50 square feet of bed. DO NOT be tempted to mix more, and do not apply unless your plants have shown the deficiency symptoms we just mentioned."],
    "parentLevel": true,
    "parentCat": null,
    "isCat": false
}, {
    "title": "Beets",
    "imageURL": "https://cdn1.medicalnewstoday.com/content/images/articles/311/311343/one-whole-beet-and-one-halved-beet.jpg",
    "climate": "cool",
    "sunlight": "6 - 8 Hours",
    "spacing": "2 - 4 Inches",
    "support": false,
    "difficulty": "beginner",
    "special": ["Till in aged manure before planting. Beets require especially good nutrition and a high phosphorus level to germinate. Go easy on nitrogen however, an excess will cause sprawling greens and tiny bulbs beneath the soil. Wait until soil reaches 50°F before planting. Plant seeds ½ inch deep and 1-2 inches apart. Make sure soil remains moist for germination. In zones with low moisture and rainfall, soak the seeds for 24 hours before planting. A soil pH between 6.0 and 7.0 is best, but slightly alkaline soils are tolerated in some areas.",
        "Beets like cool weather. In northern soils, beets shouldn’t be planted until the temperature of the soil is at least 40°F. You can plant beets in partial shade, but when growing beets, you want their roots to reach a depth of at least 3-6 inches, so don’t plant them under a tree where they might run into tree roots.",
        "Thinning is necessary, as you may get more than one seedling out of each seed. Thin when they reach about 2 inches high by pinching them off. Pulling them out of the ground may disturb the roots of nearby seedlings. Established plants should be thinned to 3–4 inches between plants. Mulch and water well. Beets need to maintain plenty of moisture."],
    "parentLevel": true,
    "parentCat": null,
    "isCat": false
}, {
    "title": "Carrots",
    "imageURL": "https://www.organicfacts.net/wp-content/uploads/2013/05/Carrot1.jpg",
    "climate": "cool",
    "sunlight": "6 - 8 Hours",
    "spacing": "1 - 3 Inches",
    "support": false,
    "difficulty": "expert",
    "special": ["Plan to plant seeds outdoors 3 to 5 weeks before the last spring frost date. Carrots are ideally grown in full sunlight, but can tolerate a moderate amount of shade. Plant carrot seeds 3 to 4 inches apart in rows. Rows should be at least a foot apart. Make sure your soil is free of stones; carrots need deeply tilled soil that they can push through.",
        "Gently mulch to retain moisture, speed germination, and block the sun from the roots. Soil should be well drained and loose to prevent forking and stunting of the root growth. Once plants are an inch tall, thin so they stand 3 inches apart. Snip them with scissors instead of pulling them out to prevent damage to the roots of remaining plants.",
        "Water at least one inch per week. Fertilize 5-6 weeks after sowing. Carrots taste much better after a couple of frosts. Following the first hard frost in the fall, cover carrot rows with an 18-inch layer of shredded leaves to preserve them for harvesting later.",
        "To produce the best crop possible, double-dig your planting area or build up a raised bed. Carrots are mature at around 2 ½ months and ½ inch in diameter. You may harvest whenever desired maturity is reached. You may leave mature carrots in the soil for storage if the ground will not freeze."],
    "parentLevel": true,
    "parentCat": null,
    "isCat": false
}, {
    "title": 'Melons',
    "description": "My melons bring all the boys to the yard.",
    "imageURL": "https://bonnieplants.com/wp-content/uploads/watermelons-istock-crop-web.jpg",
    "difficulty": "intermediate",
    "childPlants": [
        {
            "title": "Watermelon",
            "imageURL": "https://bonnieplants.com/wp-content/uploads/watermelons-istock-crop-web.jpg",
            "climate": "warm",
            "sunlight": "8 - 10 Hours",
            "spacing": "2 - 6 Feet",
            "support": true,
            "difficulty": "intermediate",
            "special": ["Watering is very important—from planting until fruit begins to form. Keep soil moist, but not waterlogged. Water at the vine’s base in the morning, and try to avoid wetting the leaves and avoid overhead watering. Reduce watering once fruit are growing. Dry weather produces the sweetest melons. If you choose to fertilize (and many do), make sure it delivers more nitrogen than phosphorus and potassium. However, after flowering begins, use a fertilizer with less nitrogen. Pruning isn’t necessary, but vine productivity may be improved if you do not allow lateral vines to grow and stick to the main vine. When the plant is young, cut off the end buds as they form. Pinch off some blossoms to focus the energy on fewer melons. Blossoms require pollination to set fruit, so be kind to the bees! As fruit is ripening, prevent rotting by gently lifting it and putting cardboard or straw between the fruit and the soil.",
                "Likes warmth. Needs long growing season of at least 70 to 85 days. If you live in warmer climates, you can sow seeds directly outdoors, but wait until the soil temperature warms to at least 70°F.",
                "While harvesting, if the watermelon sounds hollow it’s ripe. Look at the color on the top. The watermelon is ripe when there is little contrast between the stripes. Look at the color on the bottom. A green watermelon will have a white bottom; a ripe melon will have a cream- or yellow-colored bottom. Check the tendril. If it’s green, wait. If it’s half-dead, the watermelon is nearly ripe or ripe. If the tendril is fully dead, it’s ripe or overripe. Stems should be cut with a sharp knife close to the fruit."],
            "parentLevel": false,
            "parentCat": "Melons",
            "iscat": false
        }, {
            "title": "Cantaloupe",
            "imageURL": "https://maxpull-tlu7l6lqiu.stackpathdns.com/wp-content/uploads/2011/03/cantaloupe.jpg",
            "climate": "warm",
            "sunlight": "8 - 10 Hours",
            "spacing": "18 - 36 Inches",
            "support": true,
            "difficulty": "intermediate",
            "special": ["Likes warmth. Needs long growing season of at least 70 to 85 days. If you live in warmer climates, you can sow seeds directly outdoors, but wait until the soil temperature warms to at least 70°F.",
                "Amend soil with aged manure or compost before planting. Growing the vines in raised rows, known as hills, ensures good drainage and will hold the sun’s heat longer. If you are in a cooler zone, start seeds indoors about a month before transplanting. Plant seeds one inch deep, 18 inches apart, in hills about 3 feet apart.",
                "Cantaloupe likes loamy, well-drained soil. Handle them gently when you transplant. Add lots of compost to the area before planting and after planting. Mulching with black plastic will warm the soil, hinder weed growth, and keep developing fruits clean. Fertilize when vines start growing. Water in the morning, and try to avoid wetting the leaves. Reduce watering once fruit are growing. Dry weather produces the sweetest melon. If you’ve had an exceptional amount of rainfall during the ripening stage, this could cause bland fruit. Once fruit begins to grow, prune end buds off vines to increaes quality of remaining fruit. Blossoms require pollination to set fruit, so be kind to the bees!",
                "When rinds begin to change from green to tan or yellow, the melon is probably ripe, but be careful not to pick too early. Look for a crack in the stem where it attaches to the fruit. This is a sign of ripeness as well. The fruit should be easy to separate from the vine, but if they fall off by themselves they are usually overripe. Harvest melon when vines are dry, and be careful not to damage them. They will soften after harvesting, but will not continue to sweeten off the vine."],
            "parentLevel": false,
            "parentCat": "Melons",
            "iscat": false
        }, {
            "title": "Honeydew",
            "imageURL": "https://i.pinimg.com/originals/43/9b/e9/439be9c75db63fcf47be981d7e71051d.jpg",
            "climate": "warm",
            "sunlight": "8 - 10 Hours",
            "spacing": "18 - 36 Inches",
            "support": true,
            "difficulty": "intermediate",
            "special": ["Likes warmth. Needs long growing season of at least 70 to 85 days. If you live in warmer climates, you can sow seeds directly outdoors, but wait until the soil temperature warms to at least 70°F.",
                    "Amend soil with aged manure or compost before planting. Growing the vines in raised rows, known as hills, ensures good drainage and will hold the sun’s heat longer. If you are in a cooler zone, start seeds indoors about a month before transplanting. Plant seeds one inch deep, 18 inches apart, in hills about 3 feet apart.",
                "Honeydew likes loamy, well-drained soil. Handle them gently when you transplant. Add lots of compost to the area before planting and after planting. Mulching with black plastic will warm the soil, hinder weed growth, and keep developing fruits clean. Fertilize when vines start growing. Water in the morning, and try to avoid wetting the leaves. Reduce watering once fruit are growing. Dry weather produces the sweetest melon. If you’ve had an exceptional amount of rainfall during the ripening stage, this could cause bland fruit. Once fruit begins to grow, prune end buds off vines to increaes quality of remaining fruit. Blossoms require pollination to set fruit, so be kind to the bees!",
                "When rinds begin to change from green to tan or yellow, the melon is probably ripe, but be careful not to pick too early. Look for a crack in the stem where it attaches to the fruit. This is a sign of ripeness as well. The fruit should be easy to separate from the vine, but if they fall off by themselves they are usually overripe. Harvest melon when vines are dry, and be careful not to damage them. They will soften after harvesting, but will not continue to sweeten off the vine."],
            "parentLevel": false,
            "parentCat": "Melons",
            "iscat": false
        }
    ],
    "parentLevel": true,
    "parentCat": null,
    "isCat": true
}, {
    "title": "Peppers",
    "description": "Peppers mothafukka!",
    "imageURL": "https://bonnieplants.com/wp-content/uploads/pimiento-pepper.jpg",
    "difficulty": "Intermediate",
    "childplants": [
        {
            "title": "Bell Peppers",
            "imageURL": "https://img.buzzfeed.com/buzzfeed-static/static/2017-05/4/12/asset/buzzfeed-prod-fastlane-01/sub-buzz-20636-1493915918-9.jpg?downsize=715:*&output-format=auto&output-quality=auto",
            "climate": "Peppers need at least 70°F for germination, and 65°F for successful transplanting.",
            "sunlight": "6 - 8 Hours",
            "spacing": "18 - 24 Inches",
            "support": true,
            "difficulty": "intermediate",
            "special": ["Start pepper seeds three to a pot, and thin out the weakest seedling. Let the remaining two pepper plants spend their entire lives together as one plant. The leaves of two plants help protect peppers against sunscald and the yield is often twice as good as two segregated plants."],
            "parentLevel": false,
            "parentCat": "Peppers",
            "iscat": false
        }
    ],
    "parentLevel": true,
    "parentCat": null,
    "isCat": true
}, {
    "title": 'Berries',
    "description": "Berries are hardcore!",
    "imageURL": "http://www.sudburylivingmagazine.com/wp-content/uploads/2015/01/berries.jpg",
    "difficulty": "expert",
    "childPlants": [
        {
            "title": "Strawberries",
            "imageURL": "https://www.pomonafruits.co.uk/images/Strawberry-Malling-Centenary-1300312.jpg",
            "climate": "Plan to plant as soon as the ground can be worked in the Spring.",
            "sunlight": "8 - 10 Hours",
            "spacing": "20+ Inches",
            "support": false,
            "difficulty": "expert",
            "special": ["Strawberry plants come in three types: Day-Neutral, Everbearer, Junebearer. For home gardens, the recommended type is Junebearers. These produce buds during autumn, flowers and fruits the following spring, and bears fruit during summer.",
                "Although you will have to wait until the year after planting for fruit harvesting, it will be worth the wait. Tolerant of different soil types, but prefers loam. Prepare aged manure or compost several months before planting. Planting site must be well-drained so raised beds are a good option for strawberry plants. In the first year, pick off blossoms to discourage strawberry plants from bearing fruit. Instead they will develope healthier roots."],
            "parentLevel": false,
            "parentCat": "Berries",
            "iscat": false
        }, {
            "title": "Blueberries",
            "imageURL": "https://www.starkbros.com/images/dynamic/1700.jpg",
            "climate": "Bushes should be planted as early in the spring as possible.",
            "sunlight": "8 - 10 Hours",
            "spacing": "5+ Feet",
            "support": false,
            "difficulty": "expert",
            "special": ["There are three types of blueberries: Highbush, Lowbush, and Hybrid Half-high. The most commonly planted blueberry is the Highbush. Blueberries thrive in soil that is acidic. The soil pH should ideally be between 4 and 5. The more organic matter added, the more tolerance to acidity blueberries will have.",
                "When planting, dig holes about 20 inches deep and 18 inches wide. Prepare a planting mixture of 2 parts loam and one part oak leaf mold, peat moss, aged sawdust, or compost, and place a layer of this mixture in the bottom of the hole. Apply fertilizer one month after planting, not at time of planting.",
                "If you plant two-year-old blueberry plants, they should start to bear within a year or two. Pick off any flowers that form the first year or two after planting, to allow the bush to growfirst. Full production is reached after 6 years."],
            "parentLevel": false,
            "parentCat": "Berries",
            "iscat": false
        }, {
            "title": "Blackberries",
            "imageURL": "https://upload.wikimedia.org/wikipedia/commons/e/ea/Cultivated_Blackberry%2C_Rubus_fruticosus_-_geograph.org.uk_-_1426305.jpg",
            "climate": "Planting may be done in late fall, however, it should be delayed until early spring in very cold areas.",
            "sunlight": "8 - 10",
            "spacing": "5+ Feet",
            "support": true,
            "difficulty": "expert",
            "special": ["There are three basic types of blackberries: Erect Thorny, Erect Thornless, Trailing Thornless. All blackberries are perennials, meaning the roots come back year after year. However, the plant portion above the soil is biennial, meaning the plant grows vegetatively for a year, bears fruit the next year, die, then repeat.",
                "Erect blackberries produce stiff, shorter canes that come from the crown and from root suckering. Erect blackberries benefit from summer pruning. Remove the top one to two inches of new primocanes when they are four feet tall.",
                "If you have primocane-fruiting erect blackberries, cut all canes off just above the ground in the late winter for the best fruit. In the summer, when the primocanes are 3½ feet tall, removed the top 6 inches.",
                "If you have semi-erect blackberries, they are easier to manage on a Double T Trellis. Install four-foot cross arms at the top of a six-foot post. Install a three-foot cross arm about two feet below the top line. Semi-erect berries need to be pruned in the summer. When the primocanes are five feet tall, remove the top two inches to encourage branching. Several pruning sessions will be required as canes reach the appropriate height."],
            "parentLevel": false,
            "parentCat": "Berries",
            "iscat": false
        }, {
            "title": "Raspberries",
            "imageURL": "https://www.noursefarms.com/uploaded/thumbnails/tula%20magic_582_1000x1000.jpg",
            "climate": "Plant bare-root transplants in the early spring after threat of frost has passed and as soon as the soil can be worked.",
            "sunlight": "8 - 10 Hours",
            "spacing": "2 - 4 Feet",
            "support": true,
            "difficulty": "expert",
            "special": ["Prepare soil with a couple inches of compost or aged manure a couple weeks before planting. Till the soil well before planting. Before planting, soak the roots for an hour or two. Mulching is important throughout the season to conserve moisture and suffocate weeds. Keep a thick layer of mulch surrounding plants at all times. The roots send up an abundant amount of shoots, called canes. Keep order by pruning away the majority of them, so that the survivors can produce lots of berries.",
                "Red raspberries: Prune any time after the last harvest and before growth begins in the spring. Cut all canes that produced fruit to the ground. Thin to 6 sturdy canes per hill (per foot of row).",
                "Black and purple raspberries: When primocanes are between 24 to 30 inches in height, pinch out the tip of each shoot to induce branching. This will make the fruit easier to pick and increase production. After harvest, cut down all canes that bore fruit to ground level.",
                "Ever-bearing or fall-bearing raspberries: Cut all canes to the ground any time after harvest and before growth begins in the spring. Mow them to the ground or use pruning shears for a small patch.",
                "All varieties will begin to produce fruit in their second season. In some cases, ever-bearers may bear small berries in their first autumn. In early summer, berries will ripen over a time of about 2 weeks. You will need to pick berries every couple of days. Try to harvest berries on a sunny day, when they are dry. Don’t tug too hard on your raspberries when picking. A ripe raspberry will leave the vine willingly."],
            "parentLevel": false,
            "parentCat": "Berries",
            "iscat": false
        }
    ],
    "parentLevel": true,
    "parentCat": null,
    "isCat": true
}
])